name: Metrics
on:
  # Schedule updates every 4 hours
  schedule: 
    - cron: "0 0/4 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push:
    contents: write
      
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    # Grant writable permission.
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          repositories_forks: yes
          repositories_skipped: |
            Hendrix-Shen/Maven
          token: ${{ secrets.METRICS_TOKEN }}